---
- hosts: sas-all
  become: yes
  become_user: root
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:

  #
  #  Create users on all hosts
  #

  - name: Ensure group "sas" exists
    group:
      name: sas
      gid: 1003
      state: present

  - name: Ensure user "sasinst" exists, set password
    user:
      name: sasinst
      uid: 501
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "lsfadmin" exists, set password
    user:
      name: lsfadmin
      uid: 502
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "sas" exists, set password
    user:
      name: sas
      uid: 503
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "sasdemo" exists, set password
    user:
      name: sasdemo
      uid: 504
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "sassrv" exists, set password
    user:
      name: sassrv
      uid: 505
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "sastrust" exists, set password
    user:
      name: sastrust
      uid: 506
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "sasadm" exists, set password
    user:
      name: sasadm
      uid: 507
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "sasevs" exists, set password
    user:
      name: sasevs
      uid: 508
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  - name: Ensure user "webanon" exists, set password
    user:
      name: webanon
      uid: 509
      password: "{{ AdminPassword | password_hash('sha512') }}"
      group: sas

  #
  # set ulimits on all hosts
  #

  - name: add ulimits
    blockinfile:
      dest: /etc/security/limits.conf
      marker: '# {mark} increase nofile and number of open processes limits for sas account'
      insertafter: 'EOF'
      block: |
        @sas             hard    nofile          20480
        @sas             soft    nofile          20480
        @sas             hard    nproc           20480
        @sas             soft    nproc           20480
    when: "inventory_hostname in groups['sasgrid-all']"

- hosts: sasgrid1
  become: yes
  become_user: root
  vars_files:
    -  /tmp/quickstart/playbooks/vars.yml

  tasks:
  - name: change permissions on /sas directory              
    file:
      path: /sas
      state: directory
      mode: 0777

  - name: create directory quickstart and set permssions
    file:
      path: /sas/quickstart
      state: directory
      owner: sasinst
      group: sas
      mode: 0777

  - name: create directory gms_install and set permssions
    file:
      path: /sas/gms_install
      state: directory
      owner: lsfadmin
      group: sas
      mode: 0755

  - name: create directory pm_install and set permssions
    file:
      path: /sas/pm_install
      state: directory
      owner: lsfadmin
      group: sas
      mode: 0755

  - name: create directory grid and set permssions
    file:
      path: /sas/grid
      state: directory
      owner: sasinst
      group: sas
      mode: 0777

  - name: create directory studioconfig and set permssions
    file:
      path: /sas/studioconfig
      state: directory
      owner: sasinst
      group: sas
      mode: 0777
